@rootURL = http://localhost:5109

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
POST {{rootURL}}/api/employees/
Content-Type: application/json
{
  "employeeNumber" : "11111111",
  "firstName" : "Serge",
  "lastName" : "Romero",
  "eMail" : "serge@mydomain.com",
  "departmentId" : "1"
}

###
PUT {{rootURL}}/api/employees/1
Content-Type: application/json
{
  "employeeNumber" : "22222222",
  "firstName" : "Serge",
  "lastName" : "Romero",
  "eMail" : "serge@mydomain.com",
  "hireDate" : "2015-03-25",
  "departmentId" : 1
}

###
DELETE {{rootURL}}/api/employees/1

###
POST {{rootURL}}/api/benefittypes/
Content-Type: application/json
{
  "name" : "Health"
}

###

GET {{rootURL}}/api/benefittypes/2/plans

###
POST {{rootURL}}/api/benefitplans/
Content-Type: application/json
{
  "name" : "Gold Health Plan",
  "description" : "Aimed at people with families.",
  "benefitTypeId" : "1"
}

###
GET {{rootURL}}/api/benefitplans/