// <auto-generated />
using System;
using Benefits.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Benefits.Infrastructure.Migrations
{
    [DbContext(typeof(BenefitsDbContext))]
    [Migration("20260630214439_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Benefits.Domain.BenefitPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EnrollmentCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BenefitTypeId");

                    b.HasIndex("EnrollmentCategoryId");

                    b.ToTable("BenefitPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BenefitTypeId = 1,
                            Description = "Basic medical coverage.",
                            EnrollmentCategoryId = 1,
                            Name = "Health Basic"
                        },
                        new
                        {
                            Id = 2,
                            BenefitTypeId = 1,
                            Description = "Enhanced medical coverage with lower deductibles.",
                            EnrollmentCategoryId = 1,
                            Name = "Health Premium"
                        },
                        new
                        {
                            Id = 3,
                            BenefitTypeId = 1,
                            Description = "Medical coverage for employee and dependents.",
                            EnrollmentCategoryId = 1,
                            Name = "Health Family"
                        },
                        new
                        {
                            Id = 4,
                            BenefitTypeId = 3,
                            Description = "Preventive and restorative dental care.",
                            EnrollmentCategoryId = 2,
                            Name = "Dental Basic"
                        },
                        new
                        {
                            Id = 5,
                            BenefitTypeId = 3,
                            Description = "Extended dental coverage including major procedures.",
                            EnrollmentCategoryId = 2,
                            Name = "Dental Premium"
                        },
                        new
                        {
                            Id = 6,
                            BenefitTypeId = 3,
                            Description = "Orthodontic treatment coverage for eligible dependents.",
                            EnrollmentCategoryId = 3,
                            Name = "Orthodontic Coverage"
                        },
                        new
                        {
                            Id = 7,
                            BenefitTypeId = 2,
                            Description = "Annual eye exams and prescription lenses.",
                            EnrollmentCategoryId = 4,
                            Name = "Vision Basic"
                        },
                        new
                        {
                            Id = 8,
                            BenefitTypeId = 2,
                            Description = "Enhanced vision benefits with higher reimbursement limits.",
                            EnrollmentCategoryId = 4,
                            Name = "Vision Premium"
                        },
                        new
                        {
                            Id = 9,
                            BenefitTypeId = 4,
                            Description = "Employer-paid life insurance coverage.",
                            EnrollmentCategoryId = 5,
                            Name = "Life Insurance Basic"
                        },
                        new
                        {
                            Id = 10,
                            BenefitTypeId = 4,
                            Description = "Optional supplemental life insurance.",
                            EnrollmentCategoryId = 5,
                            Name = "Life Insurance Enhanced"
                        });
                });

            modelBuilder.Entity("Benefits.Domain.BenefitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("BenefitTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dental"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vision"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Life Insurance"
                        });
                });

            modelBuilder.Entity("Benefits.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("Benefits.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Benefits.Domain.EmployeeEnrollment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("BenefitPlanId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeId", "BenefitPlanId");

                    b.HasIndex("BenefitPlanId");

                    b.ToTable("EmployeeEnrollments");
                });

            modelBuilder.Entity("Benefits.Domain.EnrollmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EnrollmentCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Health Core"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dental Core"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orthodontics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vision"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Life Insurance"
                        });
                });

            modelBuilder.Entity("Benefits.Domain.BenefitPlan", b =>
                {
                    b.HasOne("Benefits.Domain.BenefitType", "BenefitType")
                        .WithMany("BenefitPlans")
                        .HasForeignKey("BenefitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Benefits.Domain.EnrollmentCategory", "EnrollmentCategory")
                        .WithMany("BenefitPlans")
                        .HasForeignKey("EnrollmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenefitType");

                    b.Navigation("EnrollmentCategory");
                });

            modelBuilder.Entity("Benefits.Domain.Employee", b =>
                {
                    b.HasOne("Benefits.Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Benefits.Domain.EmployeeEnrollment", b =>
                {
                    b.HasOne("Benefits.Domain.BenefitPlan", "BenefitPlan")
                        .WithMany("Enrollments")
                        .HasForeignKey("BenefitPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Benefits.Domain.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenefitPlan");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Benefits.Domain.BenefitPlan", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Benefits.Domain.BenefitType", b =>
                {
                    b.Navigation("BenefitPlans");
                });

            modelBuilder.Entity("Benefits.Domain.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Benefits.Domain.Employee", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Benefits.Domain.EnrollmentCategory", b =>
                {
                    b.Navigation("BenefitPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
